name: Release
run-name: "Replace '${{ inputs.search }}' -> '${{ inputs.replace }}' in ${{ inputs.file }} (by @${{ github.actor }})"
on:
  workflow_dispatch:
    inputs:
      file:
        description: "Path to the text file"
        required: false
        type: string
        default: "content.txt"
      search:
        description: "String to search for"
        required: false
        type: string
        default: "tag1"
      replace:
        description: "Replacement string"
        required: false
        type: string
        default: "tag2"
permissions:
  contents: write
  packages: write
jobs:
  replace-tag:
    uses: ./.github/workflows/replace-tag-reusable.yaml
    with:
      file: ${{ inputs.file }}
      search: ${{ inputs.search }}
      replace: ${{ inputs.replace }}
