name: Release
run-name: "Replace '${{ inputs.search }}' -> '${{ inputs.replace }}' in ${{ inputs.file }} (by @${{ github.actor }})"
on:
  workflow_dispatch:
    inputs:
      file:
        description: "Path to the text file"
        required: false
        type: string
        default: "content.txt"
      search:
        description: "String to search for"
        required: false
        type: string
        default: "tag1"
      replace:
        description: "Replacement string"
        required: false
        type: string
        default: "tag2"
permissions:
  contents: write
  packages: write
jobs:
  replace-tag:
    uses: ./.github/workflows/replace-tag-reusable.yaml
    with:
      file: ${{ inputs.file }}
      search: ${{ inputs.search }}
      replace: ${{ inputs.replace }}
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: replace-tag
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
