name: Replace Tag
on:
  workflow_call:
    inputs:
      file:
        description: "Path to the text file"
        required: true
        type: string
      search:
        description: "String to search for"
        required: false
        type: string
        default: "tag1"
      replace:
        description: "Replacement string"
        required: false
        type: string
        default: "tag2"
permissions:
  contents: write
